[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[dev]
  command = "npm run dev:vite"
  port = 8080
  targetPort = 8080
  publish = "dist/spa"
  functions = "netlify/functions"
  functionsPort = 8888

[functions]
  external_node_modules = ["express", "firebase-admin"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
